spring:
  application:
    name: config-server
  cloud:
    #配置配置服务，从本地仓库shared目录下读取配置文件
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

server:
  port: 8900
#配置服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/